// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syppwzjtvosiitlypzet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5cHB3emp0dm9zaWl0bHlwemV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjI2NjksImV4cCI6MjA2MDk5ODY2OX0.rd811FyXHFVCJupnnXW8e6YR3iWfqKoztNyNn267Kfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);